(define (domain muutoorere)
    (:requirements :strips)
    (:predicates
        (at ?piece ?position) (position ?pos) (piece ?piece)
        (playerpiece ?piece ?player) (vacant ?v)
        (validmove ?position1 ?position2)
        (turn ?player) (player ?player) 
        (different ?player1 ?player2)
        (outerpos ?pos) (centrepos ?pos)
        (neighbors ?pos ?neighbor)
    )
    (:action moveouter
    :parameters (?player1 ?player2 ?pos1 ?pos2 ?piece)
    :precondition (and (player ?player1) (player ?player2)
                    (different ?player1 ?player2)
                    (position ?pos1) (position ?pos2)
                    (outerpos ?pos2)
                    (piece ?piece) (vacant ?pos2)
                    (at ?piece ?pos1)
                    (playerpiece ?piece ?player1)
                    (validmove ?pos1 ?pos2)
                    (turn ?player1))
    :effect (and (at ?piece ?pos2) (not (at ?piece ?pos1))
                 (vacant ?pos1) (not (vacant ?pos2))
                 (turn ?player2) (not(turn ?player1))
             
              )
    )
    (:action movecentre
    :parameters (?player1 ?player2 ?pos1 ?pos2 ?piece ?neighborpos ?neighborpiece)
    :precondition (and (player ?player1) (player ?player2)
                    (different ?player1 ?player2)
                    (position ?pos1) (position ?pos2)
                    (outerpos ?pos1) (centrepos ?pos2)
                    (piece ?piece) (vacant ?pos2)
                    (at ?piece ?pos1)
                    (playerpiece ?piece ?player1)
                    (validmove ?pos1 ?pos2)
                    (turn ?player1)

                    (position ?neighborpos) 
                    (piece ?neighborpiece)
                    (neighbors ?pos1 ?neighborpos)
                    (at ?neighborpiece ?neighborpos)
                    (playerpiece ?neighborpiece ?player2))
    :effect (and (at ?piece ?pos2) (not(at ?piece ?pos1))
                 (vacant ?pos1) (not (vacant ?pos2))
                 (turn ?player2) (not(turn ?player1))
           
              )
    )
)